# Generated by Django 4.0.4 on 2022-05-28 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['name']},
        ),
    ]
