# Generated by Django 4.0.4 on 2022-05-29 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagery', '0002_alter_image_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='distance',
            new_name='place',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_title',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
        migrations.RemoveField(
            model_name='location',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='location',
            name='taken_at',
        ),
    ]
