# Generated by Django 4.0.4 on 2022-05-30 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagery', '0003_rename_content_category_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-id']},
        ),
    ]
