# Generated by Django 4.0.4 on 2022-05-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagery', '0004_alter_image_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
